# Generated by Django 5.0.6 on 2024-06-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='img',
            field=models.ImageField(default='/media/03.jpg', upload_to=''),
        ),
    ]
