# Generated by Django 5.0.6 on 2024-06-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='orient',
            field=models.CharField(default='left', max_length=20),
        ),
    ]
