# Generated by Django 5.0.6 on 2024-06-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_destination_gallery_img_alter_destination_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_img', models.ImageField(default='static/images/pic01.jpg', upload_to='gallery/')),
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='gallery_img',
        ),
    ]
